In [60]:
import pandas as pd
import numpy as np

In [61]:
df = pd.read_csv("multilinear-practice.csv")

df.head()

,StudyHours,ExtraParticipation,PapersPracticed,PreviousMarks,SleepingHours,PerformanceIndex
0,5,No,2,69,8,51
1,2,Yes,8,46,4,20
2,7,Yes,5,56,7,46
3,6,Yes,5,42,8,28
4,7,No,6,53,4,41

In [62]:
df["ExtraParticipation"].unique()

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [66]:
df["ExtraParticipation"] = df['ExtraParticipation'].map(
    {
        "Yes": 1,
        "No": 0
    }
)

In [67]:
df.head()

,StudyHours,ExtraParticipation,PapersPracticed,PreviousMarks,SleepingHours,PerformanceIndex
0,5,0,2,69,8,51
1,2,1,8,46,4,20
2,7,1,5,56,7,46
3,6,1,5,42,8,28
4,7,0,6,53,4,41

In [81]:
target_label = ["PerformanceIndex"]
y = np.array(df[target_label])
X = df.drop(columns = target_label)
X.shape[1]
y.shape

(10000, 1)

In [89]:
class LinearRegression:
    def __init__(self, learning_rate=0.001, n_iterations=100):
        self.learning_rate = learning_rate
        self.n_iterations = n_iterations
        self.weights = None
        self.bias = 0
        self.loss = []

    @staticmethod
    def _mean_squared_error( y, y_hat):
        n = y.shape[0]
        error =  np.sum((y - y_hat) **2) / n

        return error 
    
    def _gradient_descent(self, X, y):
        de_dw = 0
        de_db = 0

        n = X.shape[0]
        import pdb
        # pdb.set_trace()

        y_hat = np.dot(X, self.weights) + self.bias
        print(y_hat.shape)

        de_dw = -(2/n) * np.dot( X.T , (y - y_hat))
        print(de_dw.shape)
        de_db = -(2/n) * np.sum(y - y_hat)

    
        
        self.weights -= self.learning_rate * de_dw
        self.bias -= self.learning_rate * de_db

    def fit(self,X,y):
        self.weights = np.zeros(X.shape[1])

        for _ in range(self.n_iterations):
            self._gradient_descent(X,y)
            y_hat = np.dot(self.weights,  X) + self.bias
            loss = self._mean_squared_error(y, y_hat)
            self.loss.append(loss)

    def predict(self,X):
        return np.dot(self.weights, X) + self.bias

In [90]:
model = LinearRegression()

model.fit(X,y)

(10000,)
(5, 10000)

ValueError: operands could not be broadcast together with shapes (5,) (5,10000) (5,)